# Generated by Django 5.2.4 on 2025-07-07 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estudiante', 'Estudiante'), ('doctor', 'Doctor')], max_length=15)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('codigo_matricula', models.CharField(blank=True, max_length=20, null=True)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('colegiatura', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('motivo', models.TextField()),
                ('doctor', models.ForeignKey(limit_choices_to={'tipo': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_doctor', to='usuarios.perfil')),
                ('estudiante', models.ForeignKey(limit_choices_to={'tipo': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_estudiante', to='usuarios.perfil')),
            ],
        ),
    ]
