# Generated by Django 5.2.4 on 2025-07-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='especialidad_medica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombres',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='carrera',
            field=models.CharField(blank=True, choices=[('medicina', 'Medicina'), ('enfermeria', 'Enfermería'), ('odontologia', 'Odontología'), ('psicologia', 'Psicología'), ('estadistica', 'Ing.Estadistica e Informatica')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='codigo_matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='colegiatura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('estudiante', 'Estudiante')], max_length=20),
        ),
    ]
