# Generated by Django 5.2.4 on 2025-07-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='carrera',
            field=models.CharField(blank=True, choices=[('medicina', 'Medicina Humana'), ('enfermeria', 'Enfermería'), ('odontologia', 'Odontología'), ('psicologia', 'Psicología'), ('estadistica', 'Ingeniería Estadística e Informática'), ('civil', 'Ingeniería Civil'), ('sistemas', 'Ingeniería de Sistemas'), ('electronica', 'Ingeniería Electrónica'), ('agronomia', 'Ingeniería Agronómica'), ('ambiental', 'Ingeniería Ambiental'), ('derecho', 'Derecho'), ('contabilidad', 'Contabilidad'), ('administracion', 'Administración'), ('economia', 'Economía'), ('educacion_inicial', 'Educación Inicial'), ('educacion_primaria', 'Educación Primaria'), ('educacion_secundaria', 'Educación Secundaria'), ('biologia', 'Biología'), ('matematica', 'Matemática'), ('fisica', 'Física'), ('quimica', 'Química'), ('arquitectura', 'Arquitectura'), ('zootecnia', 'Zootecnia'), ('veterinaria', 'Medicina Veterinaria')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AnalisisMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=10, null=True)),
                ('alergias', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('paciente', models.OneToOneField(limit_choices_to={'tipo': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='analisis_medico', to='usuarios.perfil')),
            ],
        ),
    ]
