# Generated by Django 5.2.4 on 2025-07-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfil_carrera_analisismedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='orden',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(),
        ),
    ]
