# Generated by Django 5.2.4 on 2025-07-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_cita_orden_alter_cita_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisismedico',
            name='enfermedades_cronicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisismedico',
            name='medicamentos_actuales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisismedico',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
